//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeHtt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrimetravelEntities : DbContext
    {
        public PrimetravelEntities()
            : base("name=PrimetravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutUs> AboutUs { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Configuration> Configuration { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<ContactDetail> ContactDetail { get; set; }
        public virtual DbSet<ContactEmail> ContactEmail { get; set; }
        public virtual DbSet<Experience> Experience { get; set; }
        public virtual DbSet<ExperienceDetail> ExperienceDetail { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceInfo> ServiceInfo { get; set; }
        public virtual DbSet<SocialNetwork> SocialNetwork { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
