//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeHtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceViewMore
    {
        public long ServiceViewMoreId { get; set; }
        public string ServiceImage { get; set; }
        public long ServiceId { get; set; }
        public string ServiceImageName { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
