//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeHtt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialNetwork
    {
        public long SocialNetworkId { get; set; }
        public string SocialNetworkName { get; set; }
        public string SocialNetworkLink { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public string SocialNetworkType { get; set; }
    }
}
